os: osx


osx_image: xcode13.1
osx_image: xcode12.3



language: node_js
node_js: '10'
script:
  - npm run build
  - travis_retry npm run travis

language: cpp
os: osx

osx_image: xcode12.3

install:
- bash setup.sh
- brew unlink python
- brew install boost
- brew install cmake
- brew install wget
- brew install coreutils
- brew install diffutils

compiler:
 - clang

jobs:
  include:
    - osx_image: xcode13.1  
    - osx_image: xcode12.2 

script:
- wget -q --show-progress --progress=bar -O solidity_0.8.12.tar.gz https://github.com/ethereum/solidity/releases/download/v0.8.12/solidity_0.8.12.tar.gz
- tar xzf solidity_0.8.12.tar.gz
- cd solidity_0.8.12/
- mkdir build
- cd build
- cmake .. && gmake

